version: "3"

services:
  bot:
    build:
      context: "."
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - API_URL = ${API_URL}
      - HUMAN_EXPERT_USERNAME = ${USERNAME_EXPERT}
      - EXPERT_CHAT_ID = ${CHAT_ID_EXPERT}
    restart: always